name: Update README Daily

on:
  schedule:
    - cron: '23 2 * * *'
  workflow_dispatch:      # Allows manual triggering for testing

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update README timestamp
        run: |
          # Replace the "Last updated on" line with the current date
          sed -i "/## 📅 Daily Update/{n;s/Last updated on: .*/Last updated on: $(date '+%Y-%m-%d')/}" README.md

      - name: Commit changes
        run: |
          git config --local user.email "haroonar32@gmail.com"
          git config --local user.name "Haroon Rasheed"
          git add README.md
          git commit -m "Update README timestamp"
          git push
